### ISSUE TITLE
Exception: Have to be online

### ISSUE THREAD

**Issue by louisoutin** [Ivsxk/RAT#12]
Hello,

Thanks a lot for sharing your work (and your code).

I am trying to run your code, but it fails with the following exception: 
`Exception: Have to be online`

I use a conda env with same versions as defined in your readme and run ./run_main.sh.

Thanks a lot,
Louis

**Comment by louisoutin** [comment]
When I change the online argument to True, I got the following error:

Traceback (most recent call last):
  File "main.py", line 1372, in <module>
    portion_reversed=False                            )
  File "main.py", line 357, in __init__
    volume_forward=volume_forward, online=online)
  File "main.py", line 85, in __init__
    self._coin_list = CoinList(end, volume_average_days, volume_forward)
NameError: name 'CoinList' is not defined

Indeed I don't see any CoinList class, is this intended?

Thanks for your help,
Louis

**Comment by louisoutin** [comment]
Actually for anyone that want to run this repo, I found the missing class CoinList there:

https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/marketdata/coinlist.py
