### ISSUE TITLE
TypeError: Panel() takes no arguments

### ISSUE THREAD

**Issue by turmeric-blend** [Ivsxk/RAT#2]
hi, im getting this error when running with Crypto-A dataset

```
Traceback (most recent call last):
  File "main.py", line 1372, in <module>
    portion_reversed=False                            )
  File "main.py", line 362, in __init__
    features=type_list)
  File "main.py", line 133, in get_global_panel
    panel = pd.Panel(items=features, major_axis=coins, minor_axis=time_index, dtype=np.float32)
TypeError: Panel() takes no arguments
```

**Comment by turmeric-blend** [comment]
sloved by reverting to pandas version 0.24
